on: push
name: "Trigger: Push"
jobs:
  # shellcheck:
  #   name: Shellcheck
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run ShellCheck
  #       uses: ludeeus/action-shellcheck@master
  write_good_job: # https://github.com/marketplace/actions/lint-markdown
    name: lint markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: write-good action step
        id: write-good
        uses: tomwhross/write-good-action@v1.5
      # Use the output from the `write-good` step
      - name: Get the write-good output
        run: echo "${{ steps.write-good.outputs.result }}"
      - name: Post comment
        uses: mshick/add-pr-comment@v1
        if: ${{ steps.write-good.outputs.result }}
        with:
          message: |
            ${{ steps.write-good.outputs.result }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default

          # https://github.com/marketplace/actions/python-flake8
  lint:
      name: python linter
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: "3.9"
        - name: Run flake8
          uses: julianwachholz/flake8-action@v2
          with:
            checkName: "Python Lint"
            # path: path/to/files
            plugins: flake8-spellcheck
            # config: path/to/flake8.ini
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  fmt:
      name: python formatter
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: psf/black@stable
